import { Injectable } from '@angular/core';
import { Observable, of } from "rxjs";
import { Zone } from './zone';

@Injectable({
  providedIn: 'root'
})
export class ZoneService {

  constructor() { }

  getZones(): Observable<Zone[]>{
    return of(this.zones);
  }

  
  zones: Zone[] = [
    new Zone("Africa/Mbabane", "Eswatini"),
    new Zone("Africa/Mogadishu", "Somalia"),
    new Zone("Africa/Monrovia", "Liberia"),
    new Zone("Africa/Nairobi", "Kenya"),
    new Zone("Africa/Ndjamena", "Chad"),
    new Zone("Africa/Niamey", "Niger"),
    new Zone("Africa/Nouakchott", "Mauritania"),
    new Zone("Africa/Ouagadougou", "Burkina Faso"),
    new Zone("Africa/Porto-Novo", "Benin"),
    new Zone("Africa/Sao_Tome", "Sao Tome and Principe"),
    new Zone("Africa/Tripoli", "Libya"),
    new Zone("Africa/Tunis", "Tunisia"),
    new Zone("Africa/Windhoek", "Namibia"),
    new Zone("America/Adak", "USA"),
    new Zone("America/Anchorage", "USA"),
    new Zone("America/Anguilla", "Anguilla"),
    new Zone("America/Antigua", "Antigua and Barbuda"),
    new Zone("America/Araguaina", "Brazil"),
    new Zone("America/Argentina/La_Rioja", "Argentina"),
    new Zone("America/Argentina/Rio_Gallegos", "Argentina"),
    new Zone("America/Argentina/Salta", "Argentina"),
    new Zone("America/Argentina/San_Juan", "Argentina"),
    new Zone("America/Argentina/San_Luis", "Argentina"),
    new Zone("America/Argentina/Tucuman", "Argentina"),
    new Zone("America/Argentina/Ushuaia", "Argentina"),
    new Zone("America/Aruba", "Aruba"),
    new Zone("America/Asuncion", "Paraguay"),
    new Zone("America/Bahia", "Brazil"),
    new Zone("America/Bahia_Banderas", "Mexico"),
    new Zone("America/Barbados", "Barbados"),
    new Zone("America/Belem", "Brazil"),
    new Zone("America/Belize", "Belize"),
    new Zone("America/Blanc-Sablon", "Canada"),
    new Zone("America/Boa_Vista", "Brazil"),
    new Zone("America/Bogota", "Colombia"),
    new Zone("America/Boise", "USA"),
    new Zone("America/Buenos_Aires", "Argentina"),
    new Zone("America/Cambridge_Bay", "Canada"),
    new Zone("America/Campo_Grande", "Brazil"),
    new Zone("America/Cancun", "Mexico"),
    new Zone("America/Caracas", "Venezuela"),
    new Zone("America/Catamarca", "Argentina"),
    new Zone("America/Cayenne", "French Guiana"),
    new Zone("America/Cayman", "Cayman Islands"),
    new Zone("America/Chicago", "USA"),
    new Zone("America/Chihuahua", "Mexico"),
    new Zone("America/Ciudad_Juarez", "Mexico"),
    new Zone("America/Coral_Harbour", "Canada"),
    new Zone("America/Cordoba", "Argentina"),
    new Zone("America/Costa_Rica", "Costa Rica"),
    new Zone("America/Creston", "Canada"),
    new Zone("America/Cuiaba", "Brazil"),
    new Zone("America/Curacao", "Curacao"),
    new Zone("America/Danmarkshavn", "Greenland"),
    new Zone("America/Dawson", "Canada"),
    new Zone("America/Dawson_Creek", "Canada"),
    new Zone("America/Denver", "USA"),
    new Zone("America/Detroit", "USA"),
    new Zone("America/Dominica", "Dominica"),
    new Zone("America/Edmonton", "Canada"),
    new Zone("America/Eirunepe", "Brazil"),
    new Zone("America/El_Salvador", "El Salvador"),
    new Zone("America/Fort_Nelson", "Canada"),
    new Zone("America/Fortaleza", "Brazil"),
    new Zone("America/Glace_Bay", "Canada"),
    new Zone("America/Godthab", "Greenland"),
    new Zone("America/Goose_Bay", "Canada"),
    new Zone("America/Grand_Turk", "Turks and Caicos Islands"),
    new Zone("America/Grenada", "Grenada"),
    new Zone("America/Guadeloupe", "Guadeloupe"),
    new Zone("America/Guatemala", "Guatemala"),
    new Zone("America/Guayaquil", "Ecuador"),
    new Zone("America/Guyana", "Guyana"),
    new Zone("America/Halifax", "Canada"),
    new Zone("America/Havana", "Cuba"),
    new Zone("America/Hermosillo", "Mexico"),
    new Zone("America/Indiana/Knox", "USA"),
    new Zone("America/Indiana/Marengo", "USA"),
    new Zone("America/Indiana/Petersburg", "USA"),
    new Zone("America/Indiana/Tell_City", "USA"),
    new Zone("America/Indiana/Vevay", "USA"),
    new Zone("America/Indiana/Vincennes", "USA"),
    new Zone("America/Indiana/Winamac", "USA"),
    new Zone("America/Indianapolis", "USA"),
    new Zone("America/Inuvik", "Canada"),
    new Zone("America/Iqaluit", "Canada"),
    new Zone("America/Jamaica", "Jamaica"),
    new Zone("America/Jujuy", "Argentina"),
    new Zone("America/Juneau", "USA"),
    new Zone("America/Kentucky/Monticello", "USA"),
    new Zone("America/Kralendijk", "Caribbean Netherlands"),
    new Zone("America/La_Paz", "Bolivia"),
    new Zone("America/Lima", "Peru"),
    new Zone("America/Los_Angeles", "USA"),
    new Zone("America/Louisville", "USA"),
    new Zone("America/Lower_Princes", "Sint Maarten"),
    new Zone("America/Maceio", "Brazil"),
    new Zone("America/Managua", "Nicaragua"),
    new Zone("America/Manaus", "Brazil"),
    new Zone("America/Marigot", "Saint Martin"),
    new Zone("America/Martinique", "Martinique"),
    new Zone("America/Matamoros", "Mexico"),
    new Zone("America/Mazatlan", "Mexico"),
    new Zone("America/Mendoza", "Argentina"),
    new Zone("America/Menominee", "USA"),
    new Zone("America/Merida", "Mexico"),
    new Zone("America/Metlakatla", "USA"),
    new Zone("America/Mexico_City", "Mexico"),
    new Zone("America/Miquelon", "Saint Pierre and Miquelon"),
    new Zone("America/Moncton", "Canada"),
    new Zone("America/Monterrey", "Mexico"),
    new Zone("America/Montevideo", "Uruguay"),
    new Zone("America/Montserrat", "Montserrat"),
    new Zone("America/Nassau", "Bahamas"),
    new Zone("America/New_York", "USA"),
    new Zone("America/Nome", "USA"),
    new Zone("America/Noronha", "Brazil"),
    new Zone("America/North_Dakota/Beulah", "USA"),
    new Zone("America/North_Dakota/Center", "USA"),
    new Zone("America/North_Dakota/New_Salem", "USA"),
    new Zone("America/Ojinaga", "Mexico"),
    new Zone("America/Panama", "Panama"),
    new Zone("America/Paramaribo", "Suriname"),
    new Zone("America/Phoenix", "USA"),
    new Zone("America/Port-au-Prince", "Haiti"),
    new Zone("America/Port_of_Spain", "Trinidad and Tobago"),
    new Zone("America/Porto_Velho", "Brazil"),
    new Zone("America/Puerto_Rico", "Puerto Rico"),
    new Zone("America/Punta_Arenas", "Chile"),
    new Zone("America/Rankin_Inlet", "Canada"),
    new Zone("America/Recife", "Brazil"),
    new Zone("America/Regina", "Canada"),
    new Zone("America/Resolute", "Canada"),
    new Zone("America/Rio_Branco", "Brazil"),
    new Zone("America/Santarem", "Brazil"),
    new Zone("America/Santiago", "Chile"),
    new Zone("America/Santo_Domingo", "Dominican Republic"),
    new Zone("America/Sao_Paulo", "Brazil"),
    new Zone("America/Scoresbysund", "Greenland"),
    new Zone("America/Sitka", "USA"),
    new Zone("America/St_Barthelemy", "Saint Barthelemy"),
    new Zone("America/St_Johns", "Canada"),
    new Zone("America/St_Kitts", "Saint Kitts and Nevis"),
    new Zone("America/St_Lucia", "Saint Lucia"),
    new Zone("America/St_Thomas", "U.S. Virgin Islands"),
    new Zone("America/St_Vincent", "Saint Vincent and the Grenadines"),
    new Zone("America/Swift_Current", "Canada"),
    new Zone("America/Tegucigalpa", "Honduras"),
    new Zone("America/Thule", "Greenland"),
    new Zone("America/Thunder_Bay", "Canada"),
    new Zone("America/Tijuana", "Mexico"),
    new Zone("America/Toronto", "Canada"),
    new Zone("America/Tortola", "British Virgin Islands"),
    new Zone("America/Vancouver", "Canada"),
    new Zone("America/Whitehorse", "Canada"),
    new Zone("America/Winnipeg", "Canada"),
    new Zone("America/Yakutat", "USA"),
    new Zone("America/Yellowknife", "Canada"),
    new Zone("Antarctica/Casey", "Antarctica"),
    new Zone("Antarctica/Davis", "Antarctica"),
    new Zone("Antarctica/DumontDUrville", "Antarctica"),
    new Zone("Antarctica/Macquarie", "Macquarie Island"),
    new Zone("Antarctica/Mawson", "Antarctica"),
    new Zone("Antarctica/Palmer", "Antarctica"),
    new Zone("Antarctica/Rothera", "Antarctica"),
    new Zone("Antarctica/Syowa", "Antarctica"),
    new Zone("Antarctica/Troll", "Antarctica"),
    new Zone("Antarctica/Vostok", "Antarctica"),
    new Zone("Arctic/Longyearbyen", "Svalbard and Jan Mayen"),
    new Zone("Asia/Aden", "Yemen"),
    new Zone("Asia/Almaty", "Kazakhstan"),
    new Zone("Asia/Amman", "Jordan"),
    new Zone("Asia/Anadyr", "Russia"),
    new Zone("Asia/Aqtau", "Kazakhstan"),
    new Zone("Asia/Aqtobe", "Kazakhstan"),
    new Zone("Asia/Ashgabat", "Turkmenistan"),
    new Zone("Asia/Atyrau", "Kazakhstan"),
    new Zone("Asia/Baghdad", "Iraq"),
    new Zone("Asia/Bahrain", "Bahrain"),
    new Zone("Asia/Baku", "Azerbaijan"),
    new Zone("Asia/Bangkok", "Thailand"),
    new Zone("Asia/Barnaul", "Russia"),
    new Zone("Asia/Beirut", "Lebanon"),
    new Zone("Asia/Bishkek", "Kyrgyzstan"),
    new Zone("Asia/Brunei", "Brunei"),
    new Zone("Asia/Chita", "Russia"),
    new Zone("Asia/Choibalsan", "Mongolia"),
    new Zone("Asia/Colombo", "Sri Lanka"),
    new Zone("Asia/Damascus", "Syria"),
    new Zone("Asia/Dhaka", "Bangladesh"),
    new Zone("Asia/Dili", "East Timor"),
    new Zone("Asia/Dubai", "United Arab Emirates"),
    new Zone("Asia/Dushanbe", "Tajikistan"),
    new Zone("Asia/Famagusta", "Cyprus"),
    new Zone("Asia/Gaza", "Palestine"),
    new Zone("Asia/Hebron", "Palestine"),
    new Zone("Asia/Ho_Chi_Minh", "Vietnam"),
    new Zone("Asia/Hong_Kong", "Hong Kong"),
    new Zone("Asia/Hovd", "Mongolia"),
    new Zone("Asia/Irkutsk", "Russia"),
    new Zone("Asia/Jakarta", "Indonesia"),
    new Zone("Asia/Jayapura", "Indonesia"),
    new Zone("Asia/Jerusalem", "Israel"),
    new Zone("Asia/Kabul", "Afghanistan"),
    new Zone("Asia/Kamchatka", "Russia"),
    new Zone("Asia/Karachi", "Pakistan"),
    new Zone("Asia/Kathmandu", "Nepal"),
    new Zone("Asia/Khandyga", "Russia"),
    new Zone("Asia/Kolkata", "India"),
    new Zone("Asia/Krasnoyarsk", "Russia"),
    new Zone("Asia/Kuala_Lumpur", "Malaysia"),
    new Zone("Asia/Kuching", "Malaysia"),
    new Zone("Asia/Kuwait", "Kuwait"),
    new Zone("Asia/Macau", "Macau"),
    new Zone("Asia/Magadan", "Russia"),
    new Zone("Asia/Makassar", "Indonesia"),
    new Zone("Asia/Manila", "Philippines"),
    new Zone("Asia/Muscat", "Oman"),
    new Zone("Asia/Nicosia", "Cyprus"),
    new Zone("Asia/Novokuznetsk", "Russia"),
    new Zone("Asia/Novosibirsk", "Russia"),
    new Zone("Asia/Omsk", "Russia"),
    new Zone("Asia/Oral", "Kazakhstan"),
    new Zone("Asia/Phnom_Penh", "Cambodia"),
    new Zone("Asia/Pontianak", "Indonesia"),
    new Zone("Asia/Pyongyang", "North Korea"),
    new Zone("Asia/Qatar", "Qatar"),
    new Zone("Asia/Qostanay", "Kazakhstan"),
    new Zone("Asia/Qyzylorda", "Kazakhstan"),
    new Zone("Asia/Riyadh", "Saudi Arabia"),
    new Zone("Asia/Sakhalin", "Russia"),
    new Zone("Asia/Samarkand", "Uzbekistan"),
    new Zone("Asia/Seoul", "South Korea"),
    new Zone("Asia/Shanghai", "China"),
    new Zone("Asia/Singapore", "Singapore"),
    new Zone("Asia/Srednekolymsk", "Russia"),
    new Zone("Asia/Taipei", "Taiwan"),
    new Zone("Asia/Tashkent", "Uzbekistan"),
    new Zone("Asia/Tbilisi", "Georgia"),
    new Zone("Asia/Tehran", "Iran"),
    new Zone("Asia/Thimphu", "Bhutan"),
    new Zone("Asia/Tokyo", "Japan"),
    new Zone("Asia/Tomsk", "Russia"),
    new Zone("Asia/Ulaanbaatar", "Mongolia"),
    new Zone("Asia/Urumqi", "China"),
    new Zone("Asia/Ust-Nera", "Russia"),
    new Zone("Asia/Vientiane", "Laos"),
    new Zone("Asia/Vladivostok", "Russia"),
    new Zone("Asia/Yakutsk", "Russia"),
    new Zone("Asia/Yangon", "Myanmar"),
    new Zone("Asia/Yekaterinburg", "Russia"),
    new Zone("Asia/Yerevan", "Armenia"),
    new Zone("Atlantic/Azores", "Portugal"),
    new Zone("Atlantic/Bermuda", "Bermuda"),
    new Zone("Atlantic/Canary", "Spain"),
    new Zone("Atlantic/Cape_Verde", "Cape Verde"),
    new Zone("Atlantic/Faroe", "Faroe Islands"),
    new Zone("Atlantic/Madeira", "Portugal"),
    new Zone("Atlantic/Reykjavik", "Iceland"),
    new Zone("Atlantic/South_Georgia", "South Georgia"),
    new Zone("Atlantic/St_Helena", "Saint Helena"),
    new Zone("Atlantic/Stanley", "Falkland Islands"),
    new Zone("Australia/Adelaide", "Australia"),
    new Zone("Australia/Brisbane", "Australia"),
    new Zone("Australia/Broken_Hill", "Australia"),
    new Zone("Australia/Currie", "Australia"),
    new Zone("Australia/Darwin", "Australia"),
    new Zone("Australia/Eucla", "Australia"),
    new Zone("Australia/Hobart", "Australia"),
    new Zone("Australia/Lindeman", "Australia"),
    new Zone("Australia/Lord_Howe", "Australia"),
    new Zone("Australia/Melbourne", "Australia"),
    new Zone("Australia/Perth", "Australia"),
    new Zone("Australia/Sydney", "Australia"),
    new Zone("Europe/Amsterdam", "Netherlands"),
    new Zone("Europe/Andorra", "Andorra"),
    new Zone("Europe/Astrakhan", "Russia"),
    new Zone("Europe/Athens", "Greece"),
    new Zone("Europe/Belgrade", "Serbia"),
    new Zone("Europe/Berlin", "Germany"),
    new Zone("Europe/Bratislava", "Slovakia"),
    new Zone("Europe/Brussels", "Belgium"),
    new Zone("Europe/Bucharest", "Romania"),
    new Zone("Europe/Budapest", "Hungary"),
    new Zone("Europe/Busingen", "Germany"),
    new Zone("Europe/Chisinau", "Moldova"),
    new Zone("Europe/Copenhagen", "Denmark"),
    new Zone("Europe/Dublin", "Ireland"),
    new Zone("Europe/Gibraltar", "Gibraltar"),
    new Zone("Europe/Guernsey", "Guernsey"),
    new Zone("Europe/Helsinki", "Finland"),
    new Zone("Europe/Isle_of_Man", "Isle of Man"),
    new Zone("Europe/Istanbul", "Turkey"),
    new Zone("Europe/Jersey", "Jersey"),
    new Zone("Europe/Kaliningrad", "Russia"),
    new Zone("Europe/Kiev", "Ukraine"),
    new Zone("Europe/Kirov", "Russia"),
    new Zone("Europe/Lisbon", "Portugal"),
    new Zone("Europe/Ljubljana", "Slovenia"),
    new Zone("Europe/London", "United Kingdom"),
    new Zone("Europe/Luxembourg", "Luxembourg"),
    new Zone("Europe/Madrid", "Spain"),
    new Zone("Europe/Malta", "Malta"),
    new Zone("Europe/Mariehamn", "Åland Islands"),
    new Zone("Europe/Minsk", "Belarus"),
    new Zone("Europe/Monaco", "Monaco"),
    new Zone("Europe/Moscow", "Russia"),
    new Zone("Europe/Nicosia", "Cyprus"),
    new Zone("Europe/Oslo", "Norway"),
    new Zone("Europe/Paris", "France"),
    new Zone("Europe/Podgorica", "Montenegro"),
    new Zone("Europe/Prague", "Czech Republic"),
    new Zone("Europe/Riga", "Latvia"),
    new Zone("Europe/Rome", "Italy"),
    new Zone("Europe/Samara", "Russia"),
    new Zone("Europe/San_Marino", "San Marino"),
    new Zone("Europe/Sarajevo", "Bosnia and Herzegovina"),
    new Zone("Europe/Saratov", "Russia"),
    new Zone("Europe/Simferopol", "Ukraine"),
    new Zone("Europe/Skopje", "North Macedonia"),
    new Zone("Europe/Sofia", "Bulgaria"),
    new Zone("Europe/Stockholm", "Sweden"),
    new Zone("Europe/Tallinn", "Estonia"),
    new Zone("Europe/Tirane", "Albania"),
    new Zone("Europe/Ulyanovsk", "Russia"),
    new Zone("Europe/Uzhgorod", "Ukraine"),
    new Zone("Europe/Vaduz", "Liechtenstein"),
    new Zone("Europe/Vatican", "Vatican City"),
    new Zone("Europe/Vienna", "Austria"),
    new Zone("Europe/Vilnius", "Lithuania"),
    new Zone("Europe/Volgograd", "Russia"),
    new Zone("Europe/Warsaw", "Poland"),
    new Zone("Europe/Zagreb", "Croatia"),
    new Zone("Europe/Zaporozhye", "Ukraine"),
    new Zone("Indian/Antananarivo", "Madagascar"),
    new Zone("Indian/Chagos", "British Indian Ocean Territory"),
    new Zone("Indian/Christmas", "Christmas Island"),
    new Zone("Indian/Cocos", "Cocos (Keeling) Islands"),
    new Zone("Indian/Kerguelen", "French Southern and Antarctic Lands"),
    new Zone("Indian/Mahe", "Seychelles"),
    new Zone("Indian/Maldives", "Maldives"),
    new Zone("Indian/Reunion", "Réunion"),
    new Zone("Pacific/Apia", "Samoa"),
    new Zone("Pacific/Auckland", "New Zealand"),
    new Zone("Pacific/Bougainville", "Papua New Guinea"),
    new Zone("Pacific/Chatham", "New Zealand"),
    new Zone("Pacific/Chuuk", "Micronesia"),
    new Zone("Pacific/Efate", "Vanuatu"),
    new Zone("Pacific/Enderbury", "Kiribati"),
    new Zone("Pacific/Fakaofo", "Tokelau"),
    new Zone("Pacific/Fiji", "Fiji"),
    new Zone("Pacific/Funafuti", "Tuvalu"),
    new Zone("Pacific/Galapagos", "Ecuador"),
    new Zone("Pacific/Gambier", "French Polynesia"),
    new Zone("Pacific/Guadalcanal", "Solomon Islands"),
    new Zone("Pacific/Guam", "Guam"),
    new Zone("Pacific/Kiritimati", "Kiribati"),
    new Zone("Pacific/Kosrae", "Micronesia"),
    new Zone("Pacific/Kwajalein", "Marshall Islands"),
    new Zone("Pacific/Majuro", "Marshall Islands"),
    new Zone("Pacific/Marquesas", "French Polynesia"),
    new Zone("Pacific/Midway", "USA"),
    new Zone("Pacific/Nauru", "Nauru"),
    new Zone("Pacific/Niue", "Niue"),
    new Zone("Pacific/Norfolk", "Norfolk Island"),
    new Zone("Pacific/Pago_Pago", "American Samoa"),
    new Zone("Pacific/Palau", "Palau"),
    new Zone("Pacific/Pitcairn", "Pitcairn Islands"),
    new Zone("Pacific/Ponape", "Micronesia"),
    new Zone("Pacific/Port_Moresby", "Papua New Guinea"),
    new Zone("Pacific/Rarotonga", "Cook Islands"),
    new Zone("Pacific/Saipan", "Northern Mariana Islands"),
    new Zone("Pacific/Tahiti", "French Polynesia"),
    new Zone("Pacific/Tarawa", "Kiribati"),
    new Zone("Pacific/Tongatapu", "Tonga"),
    new Zone("Pacific/Wake", "USA"),
    new Zone("Pacific/Wallis", "Wallis and Futuna"),
    new Zone("Pacific/Willis", "USA"),
    new Zone("WET", "Western European Time"),
  ];

}
